name: uniquename
favicon: null
layout_spectrum: 0.29096
typography_spectrum: 0.79383
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#243026'
    - '#fece00'
    - '#fcfbf7'
    - '#7a95b3'
    - '#fc7a96'
  brandStrength: 0.31516065052710474
  lightness: 0.4309603387955576
  saturation: 0.18695877771824598
  rhythmicContrast: 0.8393964085262269
purpose: []
